// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZC1eEXnQlvrJRxysgB-OAam9VfKxX7k',
    appId: '1:105963829445:web:8718883f75053f86c058ac',
    messagingSenderId: '105963829445',
    projectId: 'todoapp-c1f98',
    authDomain: 'todoapp-c1f98.firebaseapp.com',
    storageBucket: 'todoapp-c1f98.appspot.com',
    measurementId: 'G-60571CPGJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6S55Hzur5ymgY9Q0YrsSaBD3iTVR824',
    appId: '1:105963829445:android:0840adda08090939c058ac',
    messagingSenderId: '105963829445',
    projectId: 'todoapp-c1f98',
    storageBucket: 'todoapp-c1f98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqas4KKyvoq-N3hCWkdebMsSk3kKIzww',
    appId: '1:105963829445:ios:e099af825b883e8dc058ac',
    messagingSenderId: '105963829445',
    projectId: 'todoapp-c1f98',
    storageBucket: 'todoapp-c1f98.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqas4KKyvoq-N3hCWkdebMsSk3kKIzww',
    appId: '1:105963829445:ios:e099af825b883e8dc058ac',
    messagingSenderId: '105963829445',
    projectId: 'todoapp-c1f98',
    storageBucket: 'todoapp-c1f98.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlZC1eEXnQlvrJRxysgB-OAam9VfKxX7k',
    appId: '1:105963829445:web:f2325ace8e255481c058ac',
    messagingSenderId: '105963829445',
    projectId: 'todoapp-c1f98',
    authDomain: 'todoapp-c1f98.firebaseapp.com',
    storageBucket: 'todoapp-c1f98.appspot.com',
    measurementId: 'G-RCHLNL3DWS',
  );
}
